components.json
package-lock.json
package.json
src/app/globals.css
src/components/ui/icons/BarcodeIcon.tsx
src/components/ui/icons/CardIcon.tsx
src/components/ui/icons/CloseIcon.tsx
src/components/ui/icons/CouponIcon.tsx
src/components/ui/icons/DownArrowIcon.tsx
src/components/ui/icons/DownloadIcon.tsx
src/components/ui/icons/GalleryIcon.tsx
src/components/ui/icons/InfoIcon.tsx
src/components/ui/icons/LeftArrowIcon.tsx
src/components/ui/icons/MinusIcon.tsx
src/components/ui/icons/PinCodeIcon.tsx
src/components/ui/icons/PlusIcon.tsx
src/components/ui/icons/RightArrowIcon.tsx
src/components/ui/icons/UpArrowIcon.tsx
src/lib/utils.ts

feat : SVG Icon 컴포넌트화 #7

---

src/app/test/page.tsx
src/components/ui/button.tsx

- 버튼 사이즈별 font-size, round 설정
- 버튼 컬러별 font-color, border-color 설정 #6

Feat: 공통 컴포넌트 버튼 제작 완료

---

pnpm-lock.yaml
src/app/(auth)/log-in/layout.tsx
src/app/(auth)/log-in/page.tsx
src/components/pages/auth/LogInInput.tsx
src/components/pages/auth/LogInSection.tsx
src/components/pages/auth/WelcomMessage.tsx
src/components/pages/auth/WelcomeMessage.tsx

[fix] loginpage

---

src/components/pages/main/ProductListArticle.tsx
src/components/pages/products/ProductListItem.tsx
src/data/DummyData/ProductDummyData.tsx
src/types/ProductDataTypes.ts

Merge : 상품 조회 개별 상품 컴포넌트화 및 new,best 추가 #11

Merge : 상품 조회 개별 상품 컴포넌트화 및 new,best 추가 #11

---

src/app/(main)/mypage/page.tsx
src/components/layouts/LogInHeader.tsx
src/components/pages/auth/LogInInForm.tsx
src/components/pages/auth/LogInSection.tsx
src/components/pages/mypage/DeliveryStatusPage.tsx

fix: 로그인 페이지 수정

---

src/app/(main)/best/page.tsx
src/app/(main)/event/page.tsx
src/app/(main)/layout.tsx
src/components/layouts/MenuTabModule.tsx
src/components/pages/products/ProductList.tsx
src/components/pages/products/ProductListItem.tsx
src/data/DummyData/CategoryDummyData.tsx

- svg 활용하여 랭크 아이콘 표기
- max-width 적용하여 css 버그 수정
- 기존 컴포넌트 활용 상품 리스트 표기 #29

Merge : 이벤트 페이지 제작

---

package.json
pnpm-lock.yaml
src/app/(adress)/layout.tsx
src/app/(adress)/registerAdress/page.tsx
src/app/(auth)/findid/page.tsx
src/app/(auth)/findpw/page.tsx
src/app/(auth)/login/page.tsx
src/app/test/page.tsx
src/components/layouts/SubHeader.tsx
src/components/pages/address/RegisterAdressForm.tsx
src/components/pages/auth/LogInInForm.tsx
src/components/pages/auth/LogInSection.tsx
src/components/ui/InputInfo.tsx
src/components/ui/button.tsx
src/components/ui/checkbox.tsx
src/components/ui/form.tsx
src/components/ui/forms/adressAgreeCheck.tsx
src/components/ui/icons/CloseIcon.tsx
src/components/ui/icons/GalleryIcon.tsx
src/components/ui/label.tsx
src/components/ui/select.tsx
src/components/ui/selectMemo.tsx
src/components/ui/sonner.tsx
src/components/ui/wrapper/buttonWrapper.tsx

Merge: 배송지 등록 페이지 제작(수정 필요)
- color system 지정 전 병합

Merge: 배송지 등록 페이지 제작(수정필요)

---

src/actions/signup-service/index.ts
src/app/(auth)/signup/layout.tsx
src/app/(auth)/signup/page.tsx
src/components/layouts/SignUpHeader.tsx
src/components/layouts/StickyHeader.tsx
src/components/pages/auth/signup/PolicyAgreementPage.tsx
src/components/pages/auth/signup/SignUpStep1.tsx
src/components/pages/products/ProductDetail.tsx
src/components/ui/CustomCheckbox.tsx
src/components/ui/icons/ShareIcon.tsx
src/data/InitialData.tsx
src/types/InitialDataTypes.ts

Merge : Sign Up 페이지 form형태만 제작
- 이후 퍼블리싱 공유 받은 뒤 적용하여 제작

Merge : Sign Up 페이지 form형태만 제작

---

src/actions/product-service/index.ts
src/app/(products)/products/layout.tsx
src/app/(products)/products/page.tsx
src/components/layouts/MainHeader.tsx
src/components/layouts/MenuTabModule.tsx
src/components/pages/products/ProductSubCategory.tsx
src/data/DetailData.json

Merge : 상품 태그 가져오기 구현

---

src/action/address-service/index.ts
src/app/(adress)/registerAddress/page.tsx
src/app/(adress)/searchAddress/page.tsx
src/components/layouts/SubHeader.tsx
src/components/pages/address/RegisterAddressForm.tsx
src/components/pages/address/SearchAddressForm.tsx
src/components/pages/address/SearchAddressResult.tsx
src/components/ui/InputInfo.tsx
src/types/addressApiType.ts

merge: 배송지등록 페이지 구현

---

src/actions/product-service/index.ts
src/app/(products)/products/page.tsx
src/components/layouts/MenuTabModule.tsx
src/components/pages/products/AllProductList.tsx
src/data/DetailData.json

- 페이지 새로고침시 (마운트될때) 페이지 1로 이동하게 진행
- 이전 데이터 초기화문제 (전체를 들고오는 방식으로?)
- 위 문제 해결 후 새로고침시 스크롤 위치 그대로 두는 로직 필요
- 로딩되는 중에도 페이지가 지속적으로 늘어나는 현상 해결 필요 #38

Merge : 무한스크롤 구현

---

src/components/ui/forms/defaultCheck.tsx

merge: defaultCheck 컴포넌트 오류 수정

merge: defaultCheck 컴포넌트 오류 수정

---

next.config.ts
src/action/cart-service/index.ts
src/action/product-service/index.ts
src/app/(cart)/cart/page.tsx
src/app/(cart)/layout.tsx
src/components/pages/auth/signup/NicknamePage.tsx
src/components/pages/auth/signup/SignUpSteps.tsx
src/components/pages/cart/AdressSelectSection.tsx
src/components/pages/cart/CartItem.tsx
src/components/pages/cart/CartList.tsx
src/components/pages/cart/CartSection.tsx
src/components/pages/cart/EmptyCart.tsx
src/components/pages/cart/ProductPriceInfo.tsx
src/components/pages/cart/PurchaseButtonSection.tsx
src/components/ui/SubmitButton.tsx
src/components/ui/icons/CartIcon.tsx
src/components/ui/icons/CircleMinusIcon.tsx
src/components/ui/icons/CirclePlusIcon.tsx
src/components/ui/icons/CircleXIcon.tsx
src/types/CartDataType.ts
src/types/ProductDataTypes.ts

Merge : 장바구니 기능 추가

---

README.md
src/action/product-service/index.ts
src/actions/product-service/index.ts
src/components/commons/SideBar.tsx
src/context/SessionContext.ts

Fix : fetch 기본 주소 오류 변경

---

src/action/product-service/index.ts
src/actions/signup-service/index.ts
src/app/(main)/best/page.tsx
src/app/layout.tsx
src/components/commons/SideBar.tsx
src/components/pages/auth/LogInSection.tsx
src/components/pages/auth/signup/EmailCertificationPage.tsx
src/components/pages/auth/signup/LoginInfoInputPage.tsx
src/components/pages/auth/signup/PersonalInfoPage.tsx
src/components/pages/auth/signup/PolicyAgreePage.tsx
src/components/pages/main/MainProductList.tsx
src/components/pages/products/ProductListItem.tsx
src/types/MenuTypes.ts
src/types/ProductDataTypes.ts

Merge : 베스트 상품 페이지 API 연동

---

src/components/pages/payment/OrderInfo/ShowOrderProductList.tsx
src/components/pages/payment/OrderInfo/StarbucksCard.tsx
src/components/pages/payment/StarbuckscardInfo/StarbuckscardDetail.tsx
src/components/ui/ChargeResultModal.tsx

merge: feat/paymentPage#3

---

src/action/cart-service/index.ts
src/action/event-service/index.ts
src/action/product-service/index.ts
src/app/(cart)/cart/page.tsx
src/components/pages/cart/CartCheckbox.tsx
src/components/pages/cart/CartItem.tsx
src/components/pages/cart/CartList.tsx
src/components/pages/cart/CartSection.tsx
src/components/pages/cart/ProductPriceInfo.tsx
src/components/pages/cart/PurchaseButtonSection.tsx
src/types/CartDataType.ts

Merge  : 장바구니 기능 구현

---

src/app/layout.tsx
src/components/commons/SSEListener.tsx

Merge : SSE 연결

---

src/action/event-service/index.ts
src/action/product-service/index.ts

Merge: 상품 조회 관련 cache 코드 추가

---

src/action/product-service/index.ts
src/app/(main)/mypage/myalert/page.tsx
src/components/RestockAlert/AlertCard.tsx
src/components/commons/Dialog.tsx
src/components/commons/SSEListener.tsx
src/components/commons/SideBar.tsx
src/components/pages/auth/LogInSection.tsx
src/components/pages/cart/AdressSelectSection.tsx
src/components/pages/products/OptionSelector.tsx
src/components/pages/products/ProductActionBar.tsx
src/components/pages/products/QuantitySelector.tsx
src/types/ProductDataTypes.ts

Merge : 상품/상품 알람 설정 관련 기능 추가 및 오류 수정

Merge : 상품/상품 알람 설정 관련 기능 추가 및 오류 수정

---

src/components/ui/ChargeResultModal.tsx

merge: 주문 정보 조회 수정
